output_path = "target/Junit-Index.db"
resource_paths = [
    "indexes/junit5/junit-jupiter-api/src/main/java",
    "indexes/junit5/junit-jupiter-engine/src/main/java",
    "indexes/junit5/junit-platform-engine/src/main/java"
]
allowed_packages = [
    "*"
]
build_files = [
    "indexes/junit5/pom.xml"
]
maven_home = "/opt/maven"
